/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.upf.ecp.front;

import br.upf.ecp.classes.Carro;
import javax.swing.JOptionPane;
/**
 *
 * @author kemme
 */
public class UICar extends javax.swing.JPanel {

    private Carro objCarro;
    
    public UICar() {
        initComponents();
        
        objCarro = new Carro();
        
        updateScreen();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoLiga = new javax.swing.JToggleButton();
        botaoDesliga = new javax.swing.JToggleButton();
        rotuloRPM = new javax.swing.JLabel();
        botaoAcelerar = new javax.swing.JToggleButton();
        botaoDesacelerar = new javax.swing.JToggleButton();
        rotuloMarcha = new javax.swing.JLabel();
        sliderRPM = new javax.swing.JSlider();
        sliderMarcha = new javax.swing.JSlider();
        checkboxEstado = new javax.swing.JCheckBox();
        rotuloPlaca = new javax.swing.JLabel();
        entradaPlaca = new javax.swing.JTextField();

        botaoLiga.setText("Ligar");

        botaoDesliga.setText("Desligar");

        rotuloRPM.setText("Rotações por minuto");

        botaoAcelerar.setText("Acelerar");

        botaoDesacelerar.setText("Desacelerar");

        rotuloMarcha.setText("Marcha");

        sliderRPM.setMajorTickSpacing(1000);
        sliderRPM.setMaximum(8000);
        sliderRPM.setMinorTickSpacing(1000);
        sliderRPM.setPaintLabels(true);

        sliderMarcha.setMajorTickSpacing(1);
        sliderMarcha.setMaximum(6);
        sliderMarcha.setMinorTickSpacing(1);
        sliderMarcha.setPaintLabels(true);
        sliderMarcha.setPaintTicks(true);

        checkboxEstado.setText("Ligado");

        rotuloPlaca.setText("Placa");

        entradaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaPlacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotuloPlaca)
                        .addGap(18, 18, 18)
                        .addComponent(entradaPlaca))
                    .addComponent(sliderMarcha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderRPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoDesacelerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAcelerar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoLiga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoDesliga)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxEstado))
                            .addComponent(rotuloRPM)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(rotuloMarcha)))
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloPlaca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLiga)
                    .addComponent(botaoDesliga)
                    .addComponent(checkboxEstado))
                .addGap(18, 18, 18)
                .addComponent(rotuloMarcha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderMarcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rotuloRPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sliderRPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAcelerar)
                    .addComponent(botaoDesacelerar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entradaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaPlacaActionPerformed

    private void botaoIniciarPerformed(java.awt.event.ActionEvent evt){
        try{
            objCarro.Carro(entradaPlaca.getText());
            
            updateScreen();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    private void botaoLigarPerformed(java.awt.event.ActionEvent evt) {                                             
        try{
            objCarro.power();
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }     
    }
    private void botaoDesligarPerformed(java.awt.event.ActionEvent evt) {                                             
        try{
            objCarro.power();
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }     
    }
    
    private void botaoAcelerarPerformed(java.awt.event.ActionEvent evt) {                                             
        try{
            objCarro.acelerar();
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }     
    }
    private void botaoDesacelerarPerformed(java.awt.event.ActionEvent evt) {                                             
        try{
            objCarro.desacelerar();
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }     
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoAcelerar;
    private javax.swing.JToggleButton botaoDesacelerar;
    private javax.swing.JToggleButton botaoDesliga;
    private javax.swing.JToggleButton botaoLiga;
    private javax.swing.JCheckBox checkboxEstado;
    private javax.swing.JTextField entradaPlaca;
    private javax.swing.JLabel rotuloMarcha;
    private javax.swing.JLabel rotuloPlaca;
    private javax.swing.JLabel rotuloRPM;
    private javax.swing.JSlider sliderMarcha;
    private javax.swing.JSlider sliderRPM;
    // End of variables declaration//GEN-END:variables

    private void updateScreen() {
        botaoLiga.setSelected(objCarro.getLigado());
        sliderRPM.setValue(objCarro.getRpm());
        sliderMarcha.setValue(objCarro.getMarcha());
    }
}
