/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.upf.ccc.classes.view;

import br.upf.ccc.classes.model.CarroModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Geanfrancesco Fiorini
 */
public class CarroAutomaticoView extends javax.swing.JFrame {
    private final CarroModel carro;

    /**
     * Creates new form CarroAutomaticoView
     */
    public CarroAutomaticoView() {
        initComponents();

        carro = new CarroModel(inputPlaca.getText());
        atualizaTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputPlaca = new javax.swing.JTextPane();
        btnLigar = new javax.swing.JButton();
        btnAcelerar = new javax.swing.JButton();
        btnDesacelerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inputMarcha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        slRpmAtual = new javax.swing.JSlider();
        btnLigado = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controlar Carro Automatico");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Placa:");

        jScrollPane1.setViewportView(inputPlaca);

        btnLigar.setText("Ligar");
        btnLigar.setEnabled(false);
        btnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarActionPerformed(evt);
            }
        });

        btnAcelerar.setText("Acelerar");
        btnAcelerar.setEnabled(false);
        btnAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcelerarActionPerformed(evt);
            }
        });

        btnDesacelerar.setText("Desacelerar");
        btnDesacelerar.setEnabled(false);
        btnDesacelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesacelerarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Marcha Atual:");

        inputMarcha.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("RPM Atual:");

        slRpmAtual.setMajorTickSpacing(1000);
        slRpmAtual.setMaximum(8000);
        slRpmAtual.setMinorTickSpacing(1000);
        slRpmAtual.setPaintLabels(true);
        slRpmAtual.setEnabled(false);

        btnLigado.setText("Ligado");
        btnLigado.setEnabled(false);
        btnLigado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigadoActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLigar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAcelerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesacelerar)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slRpmAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOK)
                                .addGap(18, 18, 18)
                                .addComponent(btnLigado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputMarcha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOK)
                        .addComponent(btnLigado)
                        .addComponent(jLabel3)
                        .addComponent(inputMarcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slRpmAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAcelerar)
                    .addComponent(btnDesacelerar)
                    .addComponent(btnLigar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcelerarActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAcelerarActionPerformed
        try {
            carro.acelerar();
            atualizaTela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }// GEN-LAST:event_btnAcelerarActionPerformed

    private void btnDesacelerarActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDesacelerarActionPerformed
        try {
            carro.desacelerar();
            atualizaTela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }// GEN-LAST:event_btnDesacelerarActionPerformed

    private void btnLigarActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLigarActionPerformed
        try {
            carro.power();
            atualizaTela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }// GEN-LAST:event_btnLigarActionPerformed

    private void btnLigadoActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLigadoActionPerformed

    }// GEN-LAST:event_btnLigadoActionPerformed

    private void btnOKActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnOKActionPerformed
        atualizaTela();
    }// GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (final ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarroAutomaticoView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (final InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarroAutomaticoView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (final IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarroAutomaticoView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (final javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarroAutomaticoView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarroAutomaticoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnDesacelerar;
    private javax.swing.JCheckBox btnLigado;
    private javax.swing.JButton btnLigar;
    private javax.swing.JButton btnOK;
    private javax.swing.JTextField inputMarcha;
    private javax.swing.JTextPane inputPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider slRpmAtual;
    // End of variables declaration//GEN-END:variables

    private void atualizaTela() {
        final boolean existePlaca = !(inputPlaca.getText().equals(""));
        
        btnLigado.setSelected(carro.getLigado());
        btnLigar.setEnabled(existePlaca);
        btnAcelerar.setEnabled(existePlaca);
        btnDesacelerar.setEnabled(existePlaca);
        inputPlaca.setEditable(!existePlaca);
        btnOK.setEnabled(!existePlaca);

        inputMarcha.setText(String.valueOf(carro.getMarcha()));
        slRpmAtual.setValue(carro.getRpm());
    }
}